plugins:
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.2
  NewCops: disable
  SuggestExtensions: false

Performance:
  Exclude:
    - '**/test/**/*'

Layout/LineLength:
  Max: 160

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Metrics/MethodLength:
  CountComments: false
  Max: 20
  Exclude:
    - test/**/*

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - test/**/*

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - test/**/*

Lint/UnusedMethodArgument:
  AutoCorrect: false

Style/NegatedIf:
  Enabled: false
