require:
  - rubocop-performance

AllCops:
  NewCops: disable

Performance:
  Exclude:
    - '**/test/**/*'

Layout/LineLength:
  Max: 160

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Metrics/MethodLength:
  CountComments: false
  Max: 20

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
